# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-12 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201212_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 18, 33, 32, 335154), verbose_name='Опубликована'),
        ),
    ]
