# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-12 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201212_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 19, 5, 58, 101010), verbose_name='Опубликована'),
        ),
    ]
