# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-13 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201213_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mage',
            field=models.ImageField(default='123.jpg', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 13, 20, 57, 10, 864890), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 13, 20, 57, 10, 865390), verbose_name='Дата'),
        ),
    ]
